apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: multicluster-engine
  namespace: gitops-resources
  finalizers: ["resources-finalizer.argocd.argoproj.io"] 
spec:
  project: gitops-resources
  source:
    path: ./components/multicluster-engine
    repoURL: https://github.com/rhopp/services-gitops
    targetRevision: main
  destination:
    namespace: multicluster-engine
    server: https://kubernetes.default.svc
  syncPolicy:
    managedNamespaceMetadata:
      labels: 
        argocd.argoproj.io/managed-by: openshift-gitops
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true