apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhtap-services-app-of-apps
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: openshift-gitops
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: ./app-of-apps
    repoURL: https://github.com/rhopp/services-gitops
    targetRevision: HEAD